---@class dracula.palette
---@field base0? string
---@field base01? string
---@field base02? string
---@field base03? string
---@field base04? string
---@field cyan? string
---@field diag_error? string
---@field diag_hint? string
---@field diag_info? string
---@field diag_ok? string
---@field diag_warning? string
---@field git_added? string
---@field git_modified? string
---@field git_removed? string
---@field green? string
---@field orange? string
---@field pink? string
---@field purple? string
---@field red? string
---@field shade_add? string
---@field shade_change? string
---@field shade_cyan? string
---@field shade_error? string
---@field shade_green? string
---@field shade_hint? string
---@field shade_info? string
---@field shade_ok? string
---@field shade_orange? string
---@field shade_other? string
---@field shade_pink? string
---@field shade_purple? string
---@field shade_red? string
---@field shade_warning? string
---@field shade_yellow? string
---@field yellow? string
return {
  base0 = '#F8F8F2',
  base01 = '#7B7F8B',
  base02 = '#44475A',
  base03 = '#282A36',
  base04 = '#262626',
  cyan = '#ADF6F6',
  diag_error = '#EE6666',
  diag_hint = '#8BE9FD',
  diag_info = '#8BE9FD',
  diag_ok = '#62E884',
  diag_warning = '#FFB86C',
  git_added = '#62E884',
  git_modified = '#FFB86C',
  git_removed = '#EE6666',
  green = '#62E884',
  orange = '#FFB86C',
  pink = '#F286C4',
  purple = '#BF9EEE',
  red = '#EE6666',
  shade_add = '#314742',
  shade_change = '#483F3E',
  shade_cyan = '#394552',
  shade_error = '#46333D',
  shade_green = '#314742',
  shade_hint = '#394552',
  shade_info = '#394552',
  shade_ok = '#314742',
  shade_orange = '#483F3E',
  shade_other = '#3F3B52',
  shade_pink = '#5B415A',
  shade_purple = '#3F3B52',
  shade_red = '#46333D',
  shade_warning = '#483F3E',
  shade_yellow = '#454745',
  yellow = '#E7EE98',
}
