---@class dracula.palette
---@field base0 string
---@field base01 string
---@field base02 string
---@field base03 string
---@field base04 string
---@field cyan string
---@field diag_error string
---@field diag_hint string
---@field diag_info string
---@field diag_success string
---@field diag_warning string
---@field git_added string
---@field git_modified string
---@field git_removed string
---@field green string
---@field orange string
---@field pink string
---@field purple string
---@field red string
---@field shade_add string
---@field shade_change string
---@field shade_cyan string
---@field shade_error string
---@field shade_green string
---@field shade_hint string
---@field shade_info string
---@field shade_orange string
---@field shade_pink string
---@field shade_purple string
---@field shade_red string
---@field shade_warning string
---@field shade_yellow string
---@field yellow string
return {
  base0 = '#F8F8F2',
  base01 = '#6272A4',
  base02 = '#44475A',
  base03 = '#282A36',
  base04 = '#21222C',
  cyan = '#8BE9FD',
  diag_error = '#FF5555',
  diag_hint = '#8BE9FD',
  diag_info = '#8BE9FD',
  diag_success = '#50FA7B',
  diag_warning = '#FFB86C',
  git_added = '#50FA7B',
  git_modified = '#FFB86C',
  git_removed = '#FF5555',
  green = '#50FA7A',
  orange = '#FFB86C',
  pink = '#FF79C6',
  purple = '#BD93F9',
  red = '#FF5555',
  shade_add = '#2E4940',
  shade_change = '#483F3E',
  shade_cyan = '#374754',
  shade_error = '#48303B',
  shade_green = '#2E4940',
  shade_hint = '#374754',
  shade_info = '#374754',
  shade_orange = '#483F3E',
  shade_pink = '#5E3E5A',
  shade_purple = '#3E3A53',
  shade_red = '#48303B',
  shade_warning = '#483F3E',
  shade_yellow = '#464943',
  yellow = '#F1FA8C',
}
